version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: mysql-diagnostico
    ports:
      - "3306:3306"
    env_file:
      - ../config/.env
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
